### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by Anachron** [BmanDesignsCanada/LiSpeak#77]
Hi there,

first of all, nice project! :)

I have to admit I did not install the program, but from the source code this is what I experienced:

1.) The default mode works for ubuntu/gnome desktops only. Because of that, I plan to make an elementary OS one.

2.) I am not quite sure on how to write the plugins(#2)? Which language can I use?

3.) Trying to make a global launcher with `<launch,run,start,open> [READLINE id]`, but no idea how to do it because of #2 (its already a feature request). Would solve it by lettuing linux check for path itself. Can also open folders.

4.) A list of must-havs before I can really say its useful for me(additional to #3):
- `<close,quit,exit> [READLINE id]` where id can be program or folder name
- `<minimize,hide> [READLINE id]` where id can be program or folder name
- `<show,switch to, back to> [READLINE id]` where id can be program or folder name

Some of it is already implemented in some parts, but I think its really the basics.

**Comment by BmanDesignsCanada** [comment]
I am closing this issue due to how old it is. If anyone has similar or related issues please open a new issue.
